### ISSUE TITLE
'NoneType' is not an acceptable base type when executing ansible-runner with process-isolation using a community EE base image

### ISSUE THREAD

**Issue by shantanoo-desai** [ansible/ansible-runner#1346]
## Host System

Windows Subsystem for Linux 2 with Ubuntu 22.04

### Software Versions

- __Docker Engine__: 25.0.4
- __ansible-runner__: 2.3.6
- __python__: 3.10.12

## Problem Description / Scenario

I am experimenting with `ansible-runner` to run my Runner Project via an Ansible Execution-Environment.

At the moment just to get a grip on how things work I am using the `ghcr.io/ansible-community/community-ee-base:latest` image

My inventory comprises of nothing but the `localhost` (which when executed within the EE should be the container's localhost)

Upon executing the `run` command with the respective `process-isolation` parameters via the CLI I get the following error:

```bash
Identity added: /runner/artifacts/29a525b0-49f2-47e7-aba8-780f724a7399/ssh_key_data (ansible_test_network)
ansible-playbook [core 2.16.1]
  config file = /runner/ansible.cfg
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /runner/ansible.cfg as config file
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
script declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
Parsed /runner/inventory/hosts inventory source with yaml plugin
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
ERROR! Unexpected Exception, this is probably a bug: type 'NoneType' is not an acceptable base type
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ansible/cli/__init__.py", line 659, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ansible/cli/playbook.py", line 156, in run
    results = pbex.run()
              ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ansible/executor/playbook_executor.py", line 119, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python3.12/site-packages/ansible/executor/task_queue_manager.py", line 200, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ansible/plugins/loader.py", line 864, in get
    return self.get_with_context(name, *args, **kwargs).object
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ansible/plugins/loader.py", line 899, in get_with_context
    self._module_cache[path] = self._load_module_source(resolved_type_name, path)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ansible/plugins/loader.py", line 837, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/runner/artifacts/29a525b0-49f2-47e7-aba8-780f724a7399/callback/awx_display.py", line 316, in <module>
    class CallbackModule(DefaultCallbackModule):
TypeError: type 'NoneType' is not an acceptable base type
```

### Project Structure

```bash
.
├── README.md
├── ansible.cfg
├── appstack
├── artifacts
├── env
├── inventory
├── project
└── tests
```

The `project` has all the playbooks I need to execute.

### Code Snippets

`debug.yml`

A simple ping based debug Playbook used is as follows:

```yaml
---
# project/debug.yml

- hosts: all
  gather_facts: false
  tasks:
    - name: 'ping from ee'
      ansible.builtin.ping:
```

`env/envvars`

```yaml
---
# path always relative to the `project` directory
ANSIBLE_CONFIG: ../ansible.cfg
ANSIBLE_STDOUT_CALLBACK: yaml
ANSIBLE_HOST_KEY_CHECKING: False
```

### Inventory

```yaml
inventory
├── group_vars
│   └── all
│       ├── vars.yml
│       └── vault.yml
├── host_vars
│   └── localhost.yml
└── hosts
```

content of `hosts`

```yaml
all:
  children:
    ungrouped:
      hosts:
        localhost:
```

The inventory seems to correct since on the host upon performing

```bash
ansible-inventory -i inventory --list --yaml
```

I get all the correct values for the variables and the `localhost` correctly

### Reproduction Steps

In order to execute this I am currently executing the following command in the terminal:

```bash
ansible-runner run . \
--process-isolation \
--process-isolation-executable=docker \
--container-image=ghcr.io/ansible-community/community-ee-base:latest \
-p debug.yml \
-vvv
```

Upon executing the command I get the error as mentioned above. What seems to be the problem here?

**Comment by shantanoo-desai** [comment]
## Edit

the error seems to be coming from the fact that `ANSIBLE_STDOUT_CALLBACK: yaml` is set. Upon commenting it out, I am able to execute the playbook.

I am not sure why the YAML callback plugin is throwing such an error? but my initial suspicion is the use `redirecting (type: callback) ansible.builtin.yaml to community.general.yaml` which I guess the base image might not have the `community.general` collection
