### ISSUE TITLE
ansible-runner exits unexpectedly with certain playbooks that contain unicode

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/ansible-runner#234]
```shell
cat /tmp/unicode/test.yml
---
- name: 'A play with unicode: ¢ £ ¤ ¥'
  hosts: all
  gather_facts: false
  vars:
    test_var: 'Ī ī Ĭ ĭ Į į İ ı Ĳ ĳ Ĵ ĵ Ķ ķ ĸ Ĺ ĺ Ļ ļ Ľ ľ Ŀ ŀ Ł ł Ń ń Ņ ņ Ň ň ŉ Ŋ ŋ Ō ō Ŏ ŏ Ő ő Œ'
    num_hosts: 5
    hostnames:
        - 'host-#ϬϭϮϯϰ'
        - 'host-ͰͱͲͳʹ͵'
        - 'host-ΙΚΛΜΝΞ'
        - 'host-στυφχψ'
        - 'host-ϬϭϮϯϰϱ'

  tasks:
    - name: 'A task name with unicode: è é ê ë'
      debug: msg='hi there'

    - name: 'A task with unicode parameters'
      debug: var=test_var

      # € ‚ ƒ „ … † ‡ ˆ ‰ Š ‹ Œ Ž ‘ ’ “ ” • – — ˜ ™ š › œ ž Ÿ ¡ ¢ £ ¤ ¥ ¦ § ¨ © ª « ¬ ­ ®'

    - name: 'A task using with_items containing unicode'
      debug: msg='{{item}}'
      with_items:
        - '¯ ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö ×'
        - 'Ø Ù Ú Û Ü Ý Þ ß à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ÷ ø ù ú û ü ý þ ÿ Ā'
        - 'ā Ă ă Ą ą Ć ć Ĉ ĉ Ċ ċ Č č Ď ď Đ đ Ē ē Ĕ ĕ Ė ė Ę ę Ě ě Ĝ ĝ Ğ ğ Ġ ġ Ģ ģ Ĥ ĥ Ħ ħ Ĩ ĩ'

    - add_host:
        name: '{{hostnames}}.{{item}}'
        groups: 'ĪīĬĭ'
        ansible_connection: local
        host_id: '{{item}}'
      with_sequence: start=1 end={{num_hosts}} format=%d

- name: 'A play for hosts in group: ĪīĬĭ'
  hosts: 'ĪīĬĭ'
  gather_facts: false
  tasks:
    - debug: msg='Unicode is a good thing ™'
```

Running this playbook and piping its output in python2 causes a traceback:

```
~ ansible-runner run /tmp/unicode/ -p /tmp/unicode/test.yml -i crash | tee
 [WARNING]: Unable to parse /tmp/unicode/inventory as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available


 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'



Traceback (most recent call last):
  File "/usr/bin/ansible-runner", line 9, in <module>
    load_entry_point('ansible-runner==1.3.0', 'console_scripts', 'ansible-runner')()
  File "/usr/lib/python2.7/site-packages/ansible_runner/__main__.py", line 325, in main
    res = run(**run_options)
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 159, in run
    r.run()
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner.py", line 141, in run
    searchwindowsize=100)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 179, in read_nonblocking
    self._log(s, 'read')
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 130, in _log
    second_log.write(s)
  File "/usr/lib/python2.7/site-packages/ansible_runner/utils.py", line 265, in write
    sys.stdout.write(stdout_actual + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa2' in position 29: ordinal not in range(128)
```

Notice that in this scenario, the artifact directory doesn't contain a `status` or `rc` file:

```
~ ls /tmp/unicode/artifacts/crash/
fact_cache  job_events  stdout
```

**Comment by Spredzy** [comment]
Closed as it works !

**Comment by kdelee** [comment]
Running into this again with `1.3.2`. Looks like it is running into at 
https://github.com/ansible/ansible-runner/blob/7cb34bdcd319ffeffb2f334aab24328b3347976d/ansible_runner/runner.py#L103-L109
which has been edited since that last bugfix commit mentioned on this issue.

here is the traceback:
```
/usr/bin/python2 /usr/bin/ansible-runner run /tmp/awx_21_l3aax7dd -p utf-8-䉪ቒ칸ⱷ?噂폄蔆㪗輥.yml -i 21
Traceback (most recent call last):
  File "/usr/bin/ansible-runner", line 11, in <module>
    load_entry_point('ansible-runner==1.3.2', 'console_scripts', 'ansible-runner')()
  File "/usr/lib/python2.7/site-packages/ansible_runner/__main__.py", line 329, in main
    res = run(**run_options)
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 162, in run
    r.run()
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner.py", line 108, in run
    'env': self.config.env}, f, ensure_ascii=False
  File "/usr/lib64/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
  File "/usr/lib64/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib64/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 9: ordinal not in range(128)
```

Same playbook:
https://github.com/ansible/test-playbooks/blob/master/utf-8-%E4%89%AA%E1%89%92%EC%B9%B8%E2%B1%B7%EA%AF%94%E5%99%82%ED%8F%84%E8%94%86%E3%AA%97%E8%BC%A5.yml

**Comment by kdelee** [comment]
Running into this again with `1.3.2`. Looks like it is running into at 
https://github.com/ansible/ansible-runner/blob/7cb34bdcd319ffeffb2f334aab24328b3347976d/ansible_runner/runner.py#L103-L109
which has been edited since that last bugfix commit mentioned on this issue.

here is the traceback:
```
/usr/bin/python2 /usr/bin/ansible-runner run /tmp/awx_21_l3aax7dd -p utf-8-䉪ቒ칸ⱷ?噂폄蔆㪗輥.yml -i 21
Traceback (most recent call last):
  File "/usr/bin/ansible-runner", line 11, in <module>
    load_entry_point('ansible-runner==1.3.2', 'console_scripts', 'ansible-runner')()
  File "/usr/lib/python2.7/site-packages/ansible_runner/__main__.py", line 329, in main
    res = run(**run_options)
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 162, in run
    r.run()
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner.py", line 108, in run
    'env': self.config.env}, f, ensure_ascii=False
  File "/usr/lib64/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
  File "/usr/lib64/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib64/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 9: ordinal not in range(128)
```

Same playbook:
https://github.com/ansible/test-playbooks/blob/master/utf-8-%E4%89%AA%E1%89%92%EC%B9%B8%E2%B1%B7%EA%AF%94%E5%99%82%ED%8F%84%E8%94%86%E3%AA%97%E8%BC%A5.yml

**Comment by kdelee** [comment]
also it looks like potentially same problem is faced with a limit contains unicode or a credential: getting similar problem with running `debug.yml` from `test-playbooks` but with this limit:
```
        "extra_credentials": [],                                                                                                                                                                            [0/803]
        "credentials": [
            {
                "id": 10,
                "name": "Credential - SisterEdge\uc30b",
                "description": "machine credential - \uad09\ufb2c\u0971\u56df\u2d91\u5d45\ud811\ude0c\u605f\ua397\u86f9",
                "kind": "ssh",
                "cloud": false,
                "credential_type_id": 1
            }
        ]
    },
    "created": "2019-04-11T17:07:34.318378Z",
    "modified": "2019-04-11T17:07:34.956984Z",
    "name": "JobTemplate - StorageCase\u1723",
    "description": "CourseSaltEquipmentMinuteFigureSomewherePracticeBookPleasureDrop\u0782",
    "job_type": "run",
    "inventory": 17,
    "project": 27,
    "playbook": "debug.yml",
    "forks": 0,
    "limit": "Random limit - \ud811\udc3e\ub0ab\ub136\u3bc4\ucd23\u77b5\ud821\udf75\u2c8a\u9109\u4782",
```

**Comment by kdelee** [comment]
I'm out next week so ping @Spredzy :D

**Comment by ryanpetrello** [comment]
I'm taking a look at this.

**Comment by ryanpetrello** [comment]
@Spredzy will you close this once you're satisfied with https://github.com/ansible/ansible-runner/pull/266 ?

**Comment by kdelee** [comment]
Going to close this as we've stopped running into problems on our side
