### ISSUE TITLE
--cmdline is not handled

### ISSUE THREAD

**Issue by willthames** [ansible/ansible-runner#295]
`ansible-runner --help` shows that `--cmdline` should be an option, but it is not supported by `RunnerConfig`

```
$ ansible-runner -p ../ansible-demo-operator/deploy.yml --cmdline "-e application=docker-debug -e env=test" run /tmp/ansible-operator
Traceback (most recent call last):
  File "/Users/will/src/ansible-runner/ansible_runner/__main__.py", line 329, in main
    res = run(**run_options)
  File "/Users/will/src/ansible-runner/ansible_runner/interface.py", line 161, in run
    r = init_runner(**kwargs)
  File "/Users/will/src/ansible-runner/ansible_runner/interface.py", line 64, in init_runner
    rc = RunnerConfig(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'cmdline'
```

**Comment by igor-mendix** [comment]
I've also hit this problem recently. So far I'm using the following workaround:
```python
cmdline_file = os.path.join(private_data_dir, 'env', 'cmdline')
with open(cmdline_file, 'w') as f:
    if cmdline is None:
        f.write('')
    else:
        f.write(cmdline)
```

**Comment by matburt** [comment]
see: https://github.com/ansible/ansible-runner/pull/301

**Comment by matburt** [comment]
We should be good here with the PR merge

**Comment by igor-mendix** [comment]
Thanks a lot! Works just fine.
