### ISSUE TITLE
Unicode in environment variables break ansible-runner 

### ISSUE THREAD

**Issue by rmetzler** [ansible/ansible-runner#314]
We run ansible-runner in Docker containers in Gitlab CI.
ansible-runner breaks when a user with Umlauts in his name starts the runner, as the user's name (eg. `Müller`) is saved as environment variable.

```console
[root@af4df578c2e7 /]# unset test
[root@af4df578c2e7 /]# ansible-runner -p test.yml run .
ERROR! the playbook: test.yml could not be found
[root@af4df578c2e7 /]# export test=Müller
[root@af4df578c2e7 /]# ansible-runner -p test.yml run .
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible_runner/__main__.py", line 329, in main
    res = run(**run_options)
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 162, in run
    r.run()
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner.py", line 112, in run
    'env': self.config.env}, f, ensure_ascii=False
  File "/usr/lib64/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
  File "/usr/lib64/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib64/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
[root@af4df578c2e7 /]# ansible-runner --version
1.3.4
```

## related issues

similar to #234

## link to breaking source

https://github.com/ansible/ansible-runner/blob/1696ec2075f96b57bc9099cf018ed8d0d574aed6/ansible_runner/runner.py#L109-L113

**Comment by matburt** [comment]
Can you give #315 a try?

**Comment by rmetzler** [comment]
LGTM

I had some problems checking out your branch and running it since I'm doing Python only occasionally. This is how I done it:
 
```
$ docker run -it --rm python bash
# pip install --upgrade https://github.com/matburt/ansible-runner/tarball/unicode_env
# pip install ansible
# export test=Müller
# ansible-runner -p test.yml run .
```

as one-liner:
```
docker run -it --rm -e test=Müller python /bin/bash -c "pip install --upgrade ansible https://github.com/matburt/ansible-runner/tarball/unicode_env; ansible-runner -p test.yml run ."
```

**Comment by DracoBlue** [comment]
Thanks @matburt !

**Comment by matburt** [comment]
Excellent, we'll merge this in after we verify that it passes some AWX tests.

**Comment by phlbrz** [comment]
Hello all,

@matburt 

The issue was closed but I'm having the same issue with `docker run -it ansible/ansible-runner:1.4.4 /bin/bash`

```
bash-4.2# export BLA=Tést
bash-4.2# ansible-runner --version
1.4.4
bash-4.2# ansible-runner run /runner
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible_runner/__main__.py", line 595, in main
    res = run(**run_options)
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 178, in run
    r.run()
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner.py", line 119, in run
    'env': self.config.env}, f, ensure_ascii=False
  File "/usr/lib64/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
  File "/usr/lib64/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib64/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```
