### ISSUE TITLE
extravars needs to be unicode aware

### ISSUE THREAD

**Issue by mscherfling** [ansible/ansible-runner#323]
for python 2.7, if extravars contain unicode characters, the jinja2 data merge process fails with the stacktrace:

Traceback (most recent call last):
  File "/Users/markscherfling/.pyenv/versions/2.7.15/lib/python2.7/site-packages/circuits/core/manager.py", line 856, in processTask
    raise value.extract()
FunctionException_: Traceback (most recent call last):
  File "/Users/markscherfling/.pyenv/versions/2.7.15/lib/python2.7/site-packages/fn_ansible/components/function_ansible.py", line 78, in _fn_ansible_function
    playbook_args=extra_vars
  File "/Users/markscherfling/.pyenv/versions/2.7.15/lib/python2.7/site-packages/fn_ansible/lib/ansible_api.py", line 80, in run_playbook
    raise ValueError(original_exception)
ValueError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)

environment is:
ansible==2.8.1
ansible-runner==1.3.4

**Comment by matburt** [comment]
I did some work on this here: https://github.com/ansible/ansible-runner/pull/315

It doesn't look like this would help you much though. That traceback looks like it's being caught at a higher level than Runner itself... can you give me some more detail at the Runner code level?
