### ISSUE TITLE
Runner fails to load env/cmdline that includes Unicode characters in Python2

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/ansible-runner#367]
Clone the default demo project and edit `env/cmdline`:

```shell
~/dev/ansible-runner/demo cat env/cmdline
--limit Iñtërnâtiônàlizætiøn
~/dev/ansible-runner/demo ansible-runner run . -m shell -a 'pwd' --hosts localhost
Traceback (most recent call last):
  File "/home/ryanpetrello/dev/ansible-runner/ansible_runner/__main__.py", line 594, in main
    res = run(**run_options)
  File "/home/ryanpetrello/dev/ansible-runner/ansible_runner/interface.py", line 177, in run
    r = init_runner(**kwargs)
  File "/home/ryanpetrello/dev/ansible-runner/ansible_runner/interface.py", line 65, in init_runner
    rc.prepare()
  File "/home/ryanpetrello/dev/ansible-runner/ansible_runner/runner_config.py", line 173, in prepare
    self.prepare_command()
  File "/home/ryanpetrello/dev/ansible-runner/ansible_runner/runner_config.py", line 342, in prepare_command
    self.command = self.generate_ansible_command()
  File "/home/ryanpetrello/dev/ansible-runner/ansible_runner/runner_config.py", line 367, in generate_ansible_command
    args = shlex.split(cmdline_args)
  File "/usr/lib64/python2.7/shlex.py", line 275, in split
    lex = shlex(s, posix=posix)
  File "/usr/lib64/python2.7/shlex.py", line 25, in __init__
    instream = StringIO(instream)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 9: ordinal not in range(128)
```

This only happens in Python2, not Python3.

**Comment by matburt** [comment]
Merged
