### ISSUE TITLE
Docker build fails on cryptography compilation

### ISSUE THREAD

**Issue by mancubus77** [ansible/ansible-runner#636]
Docker build fails with error:
```
docker build . -t i1

<...skip happy messages...>

Collecting cryptography (from ansible-base<2.11,>=2.10.5->ansible)
  Downloading https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz (546kB)
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ov37i7jd/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ov37i7jd/cryptography/
The command '/bin/sh -c dnf install -y epel-release &&     dnf install -y ansible-runner python3-pip sudo rsync openssh-clients sshpass glibc-langpack-en &&     alternatives --set python /usr/bin/python3 &&     pip3 install ansible &&     chmod +x /bin/tini /bin/entrypoint &&     rm -rf /var/cache/dnf' returned a non-zero code: 1
```

Git version: d40ff590 1.4.7

**Comment by jandd** [comment]
The fix is as simple as this:

```
diff --git a/Dockerfile b/Dockerfile
index 4ca9450..21c6643 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -11,6 +11,7 @@ ADD https://releases.ansible.com/ansible-runner/ansible-runner.el8.repo /etc/yum
 RUN dnf install -y epel-release && \
     dnf install -y ansible-runner python3-pip sudo rsync openssh-clients sshpass glibc-langpack-en && \
     alternatives --set python /usr/bin/python3 && \
+    pip3 install -U pip && \
     pip3 install ansible && \
     chmod +x /bin/tini /bin/entrypoint && \
     rm -rf /var/cache/dnf
```
newer versions of pip depend on setuptools_rust and are sufficient to build the image.
