### ISSUE TITLE
open_fifo_write TypeError exception for ssh-key in the second playbook

### ISSUE THREAD

**Issue by kairoaraujo** [ansible/ansible-runner#807]
I discovered if I make a loop with two playbooks to be executed in sequence (not async) using the same parameters.
The first playbook will execute properly. During the second one, I will get a TypeError exception related to the ``ssh-key``.

Example:
```python
for playbook in playbooks_list:
    ansible_response = ansible_runner.run(
        private_data_dir=private_data_dir,
        playbook=f"{playbook_dir}/{playbook}",
        inventory=f"{inventory_dir}/hosts",
        extravars=extravars,
        envvars=envvars,
        ssh_key=ssh_key,
        cmdline="-b",
        json_mode=True,
    )
```

```python
[2021-08-29 06:06:38,487: WARNING/ForkPoolWorker-2] Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/ansible_runner/utils/__init__.py", line 368, in <lambda>
    threading.Thread(target=lambda p, d: open(p, 'wb').write(d),
TypeError: a bytes-like object is required, not 'str'

[2021-08-29 06:06:38,487: WARNING/ForkPoolWorker-2]
```

I don't know if it is the proper solution, but I did it to workaround in ``ansible_runner/utils/__init__.py``:

```python
def open_fifo_write(path, data):
    '''open_fifo_write opens the fifo named pipe in a new thread.
    This blocks the thread until an external process (such as ssh-agent)
    reads data from the pipe.
    '''
    if type(data) == str:
        data = data.encode()

    os.mkfifo(path, stat.S_IRUSR | stat.S_IWUSR)
    threading.Thread(target=lambda p, d: open(p, 'wb').write(d),
                     args=(path, data)).start()
```

It is a valid solution; I can submit a PR. TIA

**Comment by chrismeyersfsu** [comment]
@kairoaraujo 

```
I discovered if I make a loop with two playbooks to be executed in sequence (not async) using the same parameters.
The first playbook will execute properly. During the second one, I will get a TypeError exception related to the ssh-key.
```

Correct, we write the ssh key to a named pipe to reduce the chance of the secret getting compromised.

As you noted, we do this by spawning a Thread and writing to the named pipe in the "background". I _think_ we could do better. In the main process, we could wait for the thread to at least start and block at the first write. Could you try this and see if it works?

**Comment by Akasurde** [comment]
Type checking for `data` is done via PR https://github.com/ansible/ansible-runner/pull/1000. Closing this issue, please feel free to re-open if the problem persists. Thanks.
