### ISSUE TITLE
[Question] How to disable env/passwords to be created

### ISSUE THREAD

**Issue by FloLaco** [ansible/ansible-runner#809]
Hi,

I run `ansible-runner` by providing password with a dict. It run with success. If I re-run the script. It's not working anymore.
The issue is, when I run the first time the script, `ansible-runner` create a the file `env/passwords` with the content of what I provided with my dict.
If I remove manually this folder, my script is working, but again, it re create the file ...

How to disable the creation of this sensitive file ?

```
import ansible_runner
passwords = {"SSH password:": "MYPASSWORD"}
r = ansible_runner.run(private_data_dir='/home/florian/ansible-runner-test', playbook='get_facts.yaml', inventory="myhosts", passwords=passwords)
print("{}: {}".format(r.status, r.rc))
# successful: 0
for each_host_event in r.events:
    print(each_host_event['event'])
print("Final status:")
print(r.stats)
```

Here's the error on my second run : 
```
(ansible-runner) florian@dsrauto-dev1:~/ansible-runner-test$ python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    r = ansible_runner.run(private_data_dir='/home/florian/ansible-runner-test', playbook='get_facts.yaml', inventory="myhosts", passwords=passwords)
  File "/home/florian/.pyenv/versions/ansible-runner/lib/python3.8/site-packages/ansible_runner/interface.py", line 254, in run
    r = init_runner(**kwargs)
  File "/home/florian/.pyenv/versions/ansible-runner/lib/python3.8/site-packages/ansible_runner/interface.py", line 119, in init_runner
    rc.prepare()
  File "/home/florian/.pyenv/versions/ansible-runner/lib/python3.8/site-packages/ansible_runner/config/runner.py", line 144, in prepare
    self.prepare_env()
  File "/home/florian/.pyenv/versions/ansible-runner/lib/python3.8/site-packages/ansible_runner/config/runner.py", line 182, in prepare_env
    super(RunnerConfig, self)._prepare_env()
  File "/home/florian/.pyenv/versions/ansible-runner/lib/python3.8/site-packages/ansible_runner/config/_base.py", line 158, in _prepare_env
    for pattern, password in iteritems(self.passwords)
  File "/home/florian/.pyenv/versions/ansible-runner/lib/python3.8/site-packages/six.py", line 605, in iteritems
    return iter(d.items(**kw))
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by FloLaco** [comment]
Oh, I found a bug https://github.com/ansible/ansible-runner/blob/fe3c1aa865898d4a173079ea846f9af5adc79e32/ansible_runner/config/_base.py#L153

`dict.update()` return `None`, so you can't assign `self.passwords.update()` to `self.passwords`

**Comment by FloLaco** [comment]
I found the same bug : https://github.com/ansible/ansible-runner/issues/493
