### ISSUE TITLE
inventory file dumped to disk is read only. 

### ISSUE THREAD

**Issue by m4ri0g** [ansible/ansible-runner#853]
I use a script to pass the host where to execute a playbook. the hosts are passed as arguments. 
on the first iteration the script runs fine and the playbook is executed. 
if the arguments change the script fails with permission denied. 

```
./test_runner.py -H vmtst4 vmtst8 toto

PLAY [all] *********************************************************************

TASK [debug output] ************************************************************
ok: [vmtst4] => {
    "msg": "hello"
}
ok: [vmtst8] => {
    "msg": "hello"
}
ok: [toto] => {
    "msg": "hello"
}

PLAY RECAP *********************************************************************
toto                       : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
vmsectst4                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
vmsectst8                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```
if the argument change: 

```
./test_runner.py -H toto tata titi
{'toto': None, 'tata': None, 'titi': None}
{'all': {'hosts': {'toto': None, 'tata': None, 'titi': None}}}
Traceback (most recent call last):
  File "./test_runner.py", line 62, in <module>
    r = ansible_runner.run(private_data_dir='.', inventory=inv, playbook='pb2.yml')
  File "/usr/home/secops_ansible/ansible/lib/python3.6/site-packages/ansible_runner/interface.py", line 254, in run
    r = init_runner(**kwargs)
  File "/usr/home/secops_ansible/ansible/lib/python3.6/site-packages/ansible_runner/interface.py", line 55, in init_runner
    dump_artifacts(kwargs)
  File "/usr/home/secops_ansible/ansible/lib/python3.6/site-packages/ansible_runner/utils/__init__.py", line 195, in dump_artifacts
    kwargs['inventory'] = dump_artifact(json.dumps(obj), path, 'hosts.json')
  File "/usr/home/secops_ansible/ansible/lib/python3.6/site-packages/ansible_runner/utils/__init__.py", line 129, in dump_artifact
    with open(fn, 'w') as f:
PermissionError: [Errno 13] Permission denied: './inventory/hosts.json
```
a host.json is dumped to disk to the inventory directory with read only permissions. 

 ls -l inventory/
total 4
-r--------. 1 secops_ansible secops_ansible 72 Sep 28 16:56 hosts.json

since the inventory is passed directly in the script as a python dictionary, there should either not be a dump to disk or at least be created with read-write permissions for the owner.

**Comment by gdeleon23** [comment]
Same to me here, in my case is python3.8

**Comment by iamgini** [comment]
Anyone found a solution for this ?

```shell
$ python -V
Python 3.9.10

$ ansible-runner --version
2.1.2

$ ansible --version
ansible [core 2.12.3]
```

```python
## passing hosts dynamically 
    hosts = {
        'hosts': {
            'Ubuntu-20-CP': {
                'ansible_host': '192.168.56.35',
                'ansible_user': 'devops',
                'ansible_password': 'devops'
            }
        },
    }
.
.
    ## build kwargs for passing to runner
    kwargs = {
        'playbook': playbook_file,
        'inventory': {'all': hosts},
        'extravars': extravars,
        'private_data_dir': 'ansible_data'
    }
```

Then the file will be created with `600` permission.

```shell
$ ls -l ansible_data/inventory
total 24
-rwxr-xr-x@ 1 gini  staff   96  5 Mar 10:32 hosts
-r--------  1 gini  staff  235  5 Mar 11:12 hosts.json
```

Then ansible will say, 

```shell
[WARNING]: Unable to parse ...ansible/ansible_data/project/ansible_data/inventory/this_inventory as an
inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
```


Any luck ?

@samdoran @m4ri0g @gdeleon23

**Comment by Bellaby** [comment]
This issue has started to appear for me in Ubuntu 20.04.

`hosts.json` is read only for the user and nothing else. When it comes to adding a new dictionary of hosts to the next `ansible_runner.run(inventory=inv)` run it throws a `Permission Error: [Errno 13] Permission denied` traceback.

Directories are in the user's home and all directories have the users and group '755' (of the same name) permissions. Not sure if that's a reason.

**Comment by Bellaby** [comment]
I've done a workaround using `os.chmod()` with mode of `600` before and after running the `ansible_runner.run()` in Python.

for example and by no means tidy:
```
os.chmod('/<private_dir>/inventory/hosts.json', 0o600)
ar = ansible_runner.run(private_data_dir="/<private_dir>", inventory=inventory, playbook="playbook.yml")
os.chmod('/<private_dir>/inventory/hosts.json', 0o600)
```

Obviously, the user running the script needs the correct permissions.

**Comment by taizi19881227** [comment]
![image](https://user-images.githubusercontent.com/47593792/209045207-bb9435d0-d3a2-43f5-ae75-0c476af7e3d9.png)
写入文件时权限给了 400

**Comment by taizi19881227** [comment]
第一次执行 run 后，会将资源清单文件写入到 inventory/hosts 文件中，或者将动态类型的 inventory 写入到 inventory/hosts.json 中，然后将 hosts 或 hosts.json 设置为了 400 权限。因此再次执行时，如果清单文件变了，就无法再写入了，不确定这是否是个bug，或者有参数设置

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible/ansible-runner/pull/1183
