### ISSUE TITLE
eventlet 0.20.0 and newer doesn't work with ansibler-runner

### ISSUE THREAD

**Issue by cubeek** [ansible/ansible-runner#90]
ansible-runner uses pexpect that uses poll() for child processes monitoring. select.poll() has been removed from eventlet in 0.20.0 and projects like OpenStack that use eventlet monkey_patching cannot use ansible-runner.

2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking Traceback (most recent call last):
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/opt/stack/networking-ansible/networking_ansible/ansible_networking.py", line 129, in vlan_access_port
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     segmentation_id, switch_port)
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/opt/stack/networking-ansible/networking_ansible/ansible_networking.py", line 75, in _run_task
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     inventory=self.inventory)
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 94, in run
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     r.run()
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/usr/lib/python2.7/site-packages/ansible_runner/runner.py", line 105, in run
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     searchwindowsize=100)
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 341, in expect
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     timeout, searchwindowsize, async_)
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     return exp.expect_loop(timeout)
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 111, in expect_loop
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     incoming = spawn.read_nonblocking(spawn.maxread, timeout)
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/usr/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 468, in read_nonblocking
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     r = poll_ignore_interrupts([self.child_fd], timeout)
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking   File "/usr/lib/python2.7/site-packages/pexpect/utils.py", line 166, in poll_ignore_interrupts
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking     poller = select.poll()
2018-07-11 15:15:45.604 TRACE networking_ansible.ansible_networking AttributeError: 'module' object has no attribute 'poll'

**Comment by qianxi2017** [comment]
ansible project has the same issue, do you guys have any clue to solve it?

**Comment by matburt** [comment]
This issue list is for the `ansible-runner` project. You should ask on the `ansible` project mailing list or irc channel.
